name: "Terraform Deployment"

on:
  push:
    branches:
      main

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TF
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Azure Login
        run: |
          az login --service-principal \
          -u ${{ secrets.ARM_CLIENT_ID }} \
          -p ${{ secrets.ARM_CLIENT_SECRET }} \
          --tenant ${{ secrets.ARM_TENANT_ID }}
      
      - name: Role
        run:
          az role assignment create \
          --assignee-object-id "fe063322-9270-449c-924f-d987742abf69" \
          --assignee-principal-type "ServicePrincipal" \
          --role "Contributor" \
          --scope "/subscriptions/d8d6ad8c-f635-407e-81b9-4ce76f2d5a10"      

      - name: Init
        run: terraform init
      
      - name: Verify Azure Credentials
        run: |
          echo "Client ID: ${{ secrets.ARM_CLIENT_ID }}"
          echo "Tenant ID: ${{ secrets.ARM_TENANT_ID }}"
          echo "Subscription ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Debug Terraform Apply
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform-debug.log
          terraform apply -auto-approve

